Update tier-1_rgw_ibm_ssl_ms_upgrade_71GA_to_8x_latest.yaml

diff --git a/suites/squid/rgw/tier-1_rgw_ibm_ssl_ms_upgrade_71GA_to_8x_latest.yaml b/suites/squid/rgw/tier-1_rgw_ibm_ssl_ms_upgrade_71GA_to_8x_latest.yaml
--- a/suites/squid/rgw/tier-1_rgw_ibm_ssl_ms_upgrade_71GA_to_8x_latest.yaml
+++ b/suites/squid/rgw/tier-1_rgw_ibm_ssl_ms_upgrade_71GA_to_8x_latest.yaml
@@ -233,6 +233,17 @@ tests:
           config:
             commands:
               - "sleep 120"
+              - |
+                for i in {1..5}; do
+                  echo "Attempt $i: Checking endpoint https://{node_ip:ceph-pri#node5}"
+                  curl -k --silent --fail https://{node_ip:ceph-pri#node5} && break
+                  echo "Attempt $i failed. Retrying in 12 seconds..."
+                  sleep 12
+                  if [ $i -eq 5 ]; then
+                    echo "ERROR: Endpoint https://{node_ip:ceph-pri#node5} is not reachable after 5 attempts."
+                    exit 1
+                  fi
+                done
               - "radosgw-admin realm pull --rgw-realm india --url https://{node_ip:ceph-pri#node5} --access-key 21e86bce636c3aa0 --secret cf764951f1fdde5d --default"
               - "radosgw-admin period pull --url https://{node_ip:ceph-pri#node5} --access-key 21e86bce636c3aa0 --secret cf764951f1fdde5d"
               - "radosgw-admin zone create --rgw-realm india --rgw-zonegroup shared --rgw-zone secondary --endpoints https://{node_ip:node5} --access-key 21e86bce636c3aa0 --secret cf764951f1fdde5d"
